openapi: 3.0.0
info:
  description: INSPIRE-5Gplus Security API
  version: 1.0.0-oas3
  title: INSPIRE Security API
  contact:
    email: ricard.vilalta@cttc.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: slice_mgr
    description: Slice Manager calls
  - name: policy_ssla_mgr
    description: Policy and SSLA Manager calls
  - name: security_orchestrator
    description: Security Orchestrator calls
  - name: security_analytics_engine
    description: Security Analytics Engine calls
  - name: vim
    description: Virtual Infrastructure Manager
  - name: wim
    description: WAN Infrastructure Manager
paths:
  /wim:
    post:
      responses:
        '200':
          description: "ok"
      tags:
        - wim
    servers:
      - url: 'http://tapi.sdncontroller.local'
        description: Override base path for T-API SDN Controler
  /vim:
    post:
      responses:
        '200':
          description: "ok"
      tags:
        - vim
    servers:
      - url: 'http://vim.local'
        description: Override base path for VIM
  /nsi:
    get:
      tags:
        - slice_mgr
      summary: retrieve netSlice array
      operationId: get_netslice
      description: |
        List netslices
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NetSlice'
        '400':
          description: bad input parameter
    post:
      tags:
        - slice_mgr
      summary: Creates a NetSlice
      operationId: post_netslice
      description: Adds a netslice item to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetSlice'
        description: NetSlice item to add
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
    put:
      tags:
        - slice_mgr
      summary: Updates a NetSlice inventory item
      operationId: put_netslice
      description: Updates a netslice to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetSlice'
        description: NetSlice item to update
      responses:
        '200':
          description: item updated
        '400':
          description: 'invalid input, object invalid'
  '/nsi/{netslice_id}':
    delete:
      tags:
        - slice_mgr
      summary: Deletes a NetSlice inventory item
      operationId: delete_netslice
      description: Deletes a netslice to the system
      parameters:
        - in: path
          name: netslice_id
          description: NetSlice ID to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: item deleted
        '400':
          description: 'invalid input, object invalid'
  /nst:
    get:
      tags:
        - slice_mgr
      summary: retrieve NST
      operationId: get_nst
      description: |
        retrieve list of nst
      responses:
        '200':
          description: array of NST
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NST'
        '400':
          description: bad input parameter
    post:
      tags:
        - slice_mgr
      summary: creates a NST
      operationId: post_nst
      description: Adds an NST item to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NST'
        description: Inventory item to add
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
  /sec_function:
    get:
      tags:
        - security_orchestrator
      summary: retrieve security functions array
      operationId: get_sec_functions
      description: |
        List Security Functions
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SecurityFunction'
        '400':
          description: bad input parameter
    post:
      tags:
        - security_orchestrator
      summary: adds a security function
      operationId: post_security_function
      description: Adds a secfunction item to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecurityFunction'
        description: Inventory item to add
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
  /policy:
    get:
      tags:
        - policy_ssla_mgr
      summary: retrieve policy array
      operationId: get_policies
      description: |
        List policies
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
        '400':
          description: bad input parameter
    post:
      tags:
        - policy_ssla_mgr
      summary: adds a policy
      operationId: post_policy
      description: Adds a policy item to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
        description: Inventory item to add
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
  '/policy/{policy_id}':
    delete:
      tags:
        - policy_ssla_mgr
      summary: Deletes a Policy inventory item
      operationId: delete_policy
      description: Deletes a policy to the system
      parameters:
        - in: path
          name: policy_id
          description: Policy ID to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: item deleted
        '400':
          description: 'invalid input, object invalid'
  /monitoring_action:
    get:
      tags:
        - security_analytics_engine
      summary: retrieve monitoring action
      operationId: get_monitoring_action
      description: |
        retrieve list of monitoring actions
      responses:
        '200':
          description: array of monitoring actions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MonitoringAction'
        '400':
          description: bad input parameter
    post:
      tags:
        - security_analytics_engine
      summary: creates a monitoring action
      operationId: post_monitoring_action
      description: Adds a monitoring action to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonitoringAction'
        description: Inventory item to add
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
  '/monitoring_action/{action_id}':
    delete:
      tags:
        - security_analytics_engine
      summary: Deletes a Action inventory item
      operationId: delete_monitoring_action
      description: Deletes a Action to the system
      parameters:
        - in: path
          name: action_id
          description: Action ID to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: item deleted
        '400':
          description: 'invalid input, object invalid'
servers:
  - url: 'https://virtserver.swaggerhub.com/rvilalta/SecurityAPI/1.0.0'
components:
  schemas:
    ConfigParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    SecurityFunction:
      type: object
      required:
        - sf_id
        - secured_netslice_id
        - security_function_template
        - config_condition_params
      properties:
        sf_id:
          type: string
        secured_netslice_id:
          type: string
        security_function_template:
          type: string
          enum:
            - IDS
            - FIREWALL
        config_condition_params:
          type: array
          items:
            $ref: '#/components/schemas/ConfigParam'
    Policy:
      type: object
      required:
        - policy_id
        - capability
        - configurationRuleAction
        - configurationCondition
        - config_condition_params
      properties:
        policy_id:
          type: string
        capability:
          type: string
          enum:
            - slice
            - nfvo
        config_rule_action:
          type: string
          enum:
            - quarantine
            - discard
        config_condition:
          type: string
          enum:
            - firewall_setup
        config_condition_params:
          type: array
          items:
            $ref: '#/components/schemas/ConfigParam'
    MonitoringAction:
      type: object
      required:
        - action_id
        - name
        - action_type
        - element_ip
        - notify_violation
        - debug
      properties:
        action_id:
          type: string
        name:
          type: string
        action_type:
          type: string
          enum:
            - MONITOR_IDS
        element_ip:
          type: string
        notify_violation:
          type: string
          enum:
            - policy_manager
        debug:
          type: string
          enum:
            - 'True'
            - 'False'
    NST:
      type: object
      required:
        - nst_id
        - name
      properties:
        nst_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: NST1
    NetSlice:
      type: object
      required:
        - netslice_id
        - name
        - nst_id
      properties:
        netslice_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: NetSlice1
        nst_id:
          $ref: '#/components/schemas/NST'
