openapi: 3.0.0
info:
  description: INSPIRE-5Gplus Security API
  version: 1.0.0-oas3
  title: INSPIRE Security API
  contact:
    email: ricard.vilalta@cttc.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: slice_mgr
    description: Slice Manager calls
paths:
  /nsi:
    get:
      tags:
        - slice_mgr
      summary: retrieve netSlice array
      operationId: get_netslice
      description: |
        List netslices
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NetSlice'
        '400':
          description: bad input parameter
    post:
      tags:
        - slice_mgr
      summary: Creates a NetSlice
      operationId: post_netslice
      description: Adds a netslice item to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetSlice'
        description: NetSlice item to add
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
    put:
      tags:
        - slice_mgr
      summary: Updates a NetSlice inventory item
      operationId: put_netslice
      description: Updates a netslice to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetSlice'
        description: NetSlice item to update
      responses:
        '200':
          description: item updated
        '400':
          description: 'invalid input, object invalid'
  '/nsi/{netslice_id}':
    delete:
      tags:
        - slice_mgr
      summary: Deletes a NetSlice inventory item
      operationId: delete_netslice
      description: Deletes a netslice to the system
      parameters:
        - in: path
          name: netslice_id
          description: NetSlice ID to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: item deleted
        '400':
          description: 'invalid input, object invalid'
  /nst:
    get:
      tags:
        - slice_mgr
      summary: retrieve NST
      operationId: get_nst
      description: |
        retrieve list of nst
      responses:
        '200':
          description: array of NST
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NST'
        '400':
          description: bad input parameter
    post:
      tags:
        - slice_mgr
      summary: creates a NST
      operationId: post_nst
      description: Adds an NST item to the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NST'
        description: Inventory item to add
      responses:
        '200':
          description: item created
        '400':
          description: 'invalid input, object invalid'
servers:
  - url: 'https://virtserver.swaggerhub.com/rvilalta/SecurityAPI/1.0.0'
components:
  schemas:
    NST:
      type: object
      required:
        - nst_id
        - name
      properties:
        nst_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: NST1
    NetSlice:
      type: object
      required:
        - netslice_id
        - name
        - nst_id
      properties:
        netslice_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: NetSlice1
        nst_id:
          $ref: '#/components/schemas/NST'
