openapi: 3.0.0
info:
  description: INSPIRE-5Gplus Security API
  version: 1.0.0-oas3
  title: INSPIRE Security API
  contact:
    email: ricard.vilalta@cttc.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: vim
    description: Virtual Infrastructure Manager
  - name: wim
    description: WAN Infrastructure Manager
paths:
  /wim:
    post:
      responses:
        '200':
          description: "ok"
      tags:
        - wim
    servers:
      - url: 'http://tapi.sdncontroller.local'
        description: Override base path for T-API SDN Controler
  /vim:
    post:
      responses:
        '200':
          description: "ok"
      tags:
        - vim
    servers:
      - url: 'http://vim.local'
        description: Override base path for VIM

servers:
  - url: 'https://virtserver.swaggerhub.com/rvilalta/SecurityAPI/1.0.0'
